### ISSUE TITLE
Support basic typescript definitions

### ISSUE THREAD

**Issue by atomicpages** [erictooth/react-accessible-form#1]
Basic typescript definitions can be [generated with @pika/pack](https://www.pika.dev/blog/introducing-pika-pack/#3.-automatically-generate-typescript-definitions-(1-line)). When using react-accessible-form with tsc we're seeing errors like:

```
TS2307: Cannot find module 'react-accessible-form'
```

**Comment by erictooth** [comment]
No longer needed due to recent changes. Thanks!
